### ISSUE TITLE
Chef Supermarket link is broken

### ISSUE THREAD

**Issue by ironsalsa** [sophos-iaas/chef-sophos-sg#2]
https://supermarket.chef.io/cookbooks/sophos/versions/1.0.1 is pointing to your old URL - looks like you updated the URL in Git but didn't let Chef know. Sorry if this isn't exactly an issue with the code, but I'm betting you would be the team to fix this.

**Comment by threez** [comment]
Thx. I will fix the link an republish the cookbook.
